### ISSUE TITLE
Pallet error. Missing secret or db requirement

### ISSUE THREAD

**Issue by steveoh** [agrc/ugs-db#70]
```
INFO    02-06 03:23:42   programs:  228 updating WQP stations and results...
INFO    02-06 03:23:43   programs:  236 fetching records after 2017-01-26 00:00:00.0000000
INFO    02-06 03:24:22   services:  551 query completed in 0:00:35.843000
INFO    02-06 03:24:22   services:  552 new sites found 13
INFO    02-06 03:24:22   services:  553 new results found 84
INFO    02-06 03:24:47   programs:  265 all stations already in database
ERROR   02-06 03:24:47       lift:  116 error shipping pallet:  for pallet: c:\scheduled\warehouse\ugs-db\src\ugs_pallet.py:UGSPallet
Traceback (most recent call last):
  File "c:\python27\arcgis10.3\lib\site-packages\forklift\lift.py", line 111, in process_pallets
    pallet.ship()
  File "c:\scheduled\warehouse\ugs-db\src\ugs_pallet.py", line 29, in ship
    Seeder('forklift').update('WQP, SDWIS', configs_lookup[self.configuration], None, True)
  File "c:\scheduled\warehouse\ugs-db\src\ugsdbseeder\ugsdbseeder.py", line 188, in update
    arcpy=arcpy)
  File "c:\scheduled\warehouse\ugs-db\src\ugsdbseeder\programs.py", line 795, in __init__
    self.source_cursor = cursor_factory(secrets['connection_string'])
  File "c:\scheduled\warehouse\ugs-db\src\ugsdbseeder\sql.py", line 28, in create_cursor
    c = pyodbc.connect(connection_string)
Error: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
```

**Comment by stdavis** [comment]
Updated `sdwis` connection string to: `Driver={Oracle in OraClient11g_home1};UID=<username>;PWD=<password>;DBQ=sdwis;`.
